services:
  mongodb:
    image: mongo:6
    container_name: mongodb
    volumes:
      - mongo-data:/data/db

  backend:
    build: ./backend
    container_name: backend
    depends_on:
      - mongodb
    environment:
      - MONGO_URI=mongodb://mongodb:27017/cruddb
    ports:
      - "5000:5000"

  frontend:
    build: ./frontend
    container_name: frontend
    depends_on:
      - backend
    ports:
      - "80:80"

volumes:
  mongo-data:
